### ISSUE TITLE
Crash in VSCode 1.22.2

### ISSUE THREAD

**Issue by abbasnaqdi** [georgewfraser/kotlin-language-server#2]
VSCode : 1.22.2 in mac os 10.13.4
Unfortunately, it does not work for me and sends the following message : 

> The Kotlin Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

**Please check and fix it.**

**Comment by dominicparga** [comment]
@georgewfraser first of all, thanks a lot for your effort in providing this Kotlin LSP server! :)

I’m a macOS user and I have the same issue as well. Just created an empty Kotlin file (without any build tool) and tried to write a hello-world-example.

**Comment by wk-j** [comment]
Same problem

<img width="861" alt="developer_tools_-_file____applications_visual_20studio_20code_app_contents_resources_app_out_vs_workbench_electron-browser_bootstrap_index_html_config__7b_22__22_3a_5b_22_2fusers_2fwk_2fgithub_2fkotlinsyntax_22_5d_2c_22help_22_3afalse_2c_22" src="https://user-images.githubusercontent.com/860704/39790846-7092b3d6-5362-11e8-9797-3a7e9a4bc00f.png">


```
❯ /Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/Home/bin/java -Xverify:none -jar /Users/wk/.vscode/extensions/georgewfraser.kotlin-0.1.0/target/KotlinLanguageServer.jar
Exception in thread "main" java.lang.IllegalStateException: LOGGING: Loading modules: [java.se, javafx.base, javafx.controls, javafx.fxml, javafx.graphics, javafx.media, javafx.swing, javafx.web, jdk.accessibility, jdk.attach, jdk.compiler, jdk.dynalink, jdk.httpserver, jdk.incubator.httpclient, jdk.jartool, jdk.javadoc, jdk.jconsole, jdk.jdi, jdk.jfr, jdk.jshell, jdk.jsobject, jdk.management, jdk.management.cmm, jdk.management.jfr, jdk.management.resource, jdk.net, jdk.packager, jdk.packager.services, jdk.plugin.dom, jdk.scripting.nashorn, jdk.sctp, jdk.security.auth, jdk.security.jgss, jdk.unsupported, jdk.xml.dom, oracle.desktop, oracle.net, java.base, java.sql, java.logging, java.xml, java.rmi, java.scripting, java.security.sasl, java.management, java.datatransfer, java.desktop, java.xml.crypto, java.prefs, java.instrument, java.naming, java.compiler, java.sql.rowset, java.management.rmi, java.security.jgss, jdk.internal.jvmstat, jdk.management.agent, jdk.jdwp.agent, jdk.internal.ed, jdk.internal.opt, jdk.internal.le, jdk.jdeps, jdk.jlink] (no MessageCollector configured)
	at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.report(ClasspathRootsResolver.kt:314)
	at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.report$default(ClasspathRootsResolver.kt:312)
	at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.addModularRoots(ClasspathRootsResolver.kt:254)
	at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.computeRoots(ClasspathRootsResolver.kt:124)
	at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.convertClasspathRoots(ClasspathRootsResolver.kt:79)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:233)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:117)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForProduction(KotlinCoreEnvironment.kt:413)
	at org.javacs.kt.Compiler.<init>(Compiler.kt:46)
	at org.javacs.kt.CompilerClassPath.<init>(CompilerClassPath.kt:9)
	at org.javacs.kt.KotlinLanguageServer.<init>(KotlinLanguageServer.kt:14)
	at org.javacs.kt.MainKt.main(Main.kt:8)
```

**Comment by fwcd** [comment]
@wk-j This might be an incompatibility between your JDK configuration and the Kotlin API.

@dfmAbbas @dominicparga  Could you please provide a stack trace or some kind of output log? Usually, these can be found under "Output" -> dropdown menu -> "Kotlin".

**Comment by dominicparga** [comment]
@georgewfraser 
I reopened my `Kotlin`-project and there was a new error message (nothing verbose, just something like "Error occured"). Hence I wanted to reinstall your extension ("Have you tried turning it off and on again?") but the market place doesn't have this extension anymore? Can't find it, neither in my `Visual Studio Code` nor [in my browser](https://marketplace.visualstudio.com/search?term=kotlin&target=VSCode&category=All%20categories&sortBy=Relevance).

**Comment by fwcd** [comment]
@dominicparga Did you try installing [my fork](https://github.com/fwcd/KotlinLanguageServer)?

**Comment by georgewfraser** [comment]
Closing because this project has been moved to @fwcd 's fork

**Comment by dominicparga** [comment]
@fwcd Hello, sorry for my late response. I'm quite busy these days, so I can't try it now. I will try it in my next holidays. Maybe there will be a vscode extension then? (⊃｡•́‿•̀｡)⊃━☆ﾟ.*･｡ﾟ

**Comment by fwcd** [comment]
@dominicparga I have published the extension on the marketplace already: https://marketplace.visualstudio.com/items?itemName=fwcd.kotlin :)
